### ISSUE TITLE
Это что еще за авторизация?

### ISSUE THREAD

**Issue by starkovsky** [andre-w2/vue-web#4]
https://github.com/andre-w2/vue-web/blob/15dcb6ae7c297207fc428046cd29246c715f0109/src/components/Entrance.vue#L64

Страшно представить такую авторизацию, но вам почти удалось

**Comment by andre-w2** [comment]
почему почти?

**Comment by starkovsky** [comment]
Хранить пароль локально ) тут плохо все

**Comment by andre-w2** [comment]
ааа про это знаю! Это я для примера тупо сделал

**Comment by andre-w2** [comment]
исправил всё
